---
title: "Plotting statistics from using all of the CS permute reg hits to nominate for a validation screen"
output: html_notebook
---

```{r}
library(tidyverse)
library(cowplot)
library(viridis)
```


```{r}
sig_levels = seq(0.0,0.99,by=0.01)

i = 1
threshold = sig_levels[i]
reg_hit_stats = read.csv(paste0("regression_summary_stats/summary_stats_from_all_reg_sig_coef_permute_0.0_Dec102021.csv"))
reg_hit_stats = reg_hit_stats %>%filter(!((Metadata_run%in%c("CS_run3"))&Metadata_compression==2&Metadata_replicates==7))
reg_hit_stats$pool_size =(reg_hit_stats$Metadata_compression/2)*reg_hit_stats$Metadata_replicates
reg_hit_stats$Metadata_compression_fctr = factor(reg_hit_stats$Metadata_compression,levels=c(2.0,4.0,8.0,16.0,32.0))
reg_hit_stats$Metadata_replicates_fctr = factor(reg_hit_stats$Metadata_replicates,levels=c(3,5,7))
reg_hit_stats$permute_threshold = threshold

for(i in 2:length(sig_levels)){
  threshold = sig_levels[i]
  temp = read.csv(paste0("regression_summary_stats/summary_stats_from_all_reg_sig_coef_permute_",threshold,"_Dec102021.csv"))
  temp = temp %>%filter(!((Metadata_run%in%c("CS_run3"))&Metadata_compression==2&Metadata_replicates==7))
  temp$pool_size =(temp$Metadata_compression/2)*temp$Metadata_replicates
  temp$Metadata_compression_fctr = factor(temp$Metadata_compression,levels=c(2.0,4.0,8.0,16.0,32.0))
  temp$Metadata_replicates_fctr = factor(temp$Metadata_replicates,levels=c(3,5,7))
  temp$permute_threshold = threshold
  
  reg_hit_stats = rbind(reg_hit_stats,temp)
  
}

# add in a final temp with all fpr and tpr of one
# temp$tpr = 1
# temp$fpr = 1
# reg_hit_stats = rbind(reg_hit_stats,temp)

# reg_hit_stats$permute_threshold = factor(reg_hit_stats$permute_threshold,levels=sig_levels)
reg_hit_stats$pool_size = factor(reg_hit_stats$pool_size)
```


```{r}
library(MESS)
```





```{r}
# pdf("regression_summary_stats/tpr_fpr_roc_curves_run1.pdf",width = 3.5,height = 3.5,useDingbats = F)
partA = reg_hit_stats %>% filter(Metadata_run =="CS_run1")
partB = reg_hit_stats %>% filter(Metadata_run =="CS_run3") %>% filter(Metadata_scheme=="random1")
data = rbind(partA,partB) %>% filter()
data$pool_color = as.numeric(as.character(data$pool_size))
ggplot(data,aes(y=tpr,x= fpr,color=pool_color)) +geom_line(aes(group=pool_size))+ theme_classic() + ylim(0,1) + xlim(0,0.65) +
  ggtitle("Run 1") + scale_color_viridis(discrete = F,trans="log2") +labs(color="Pool size") + geom_abline(linetype = "dashed")
# dev.off()
```

```{r}
# pdf("regression_summary_stats/tpr_fpr_roc_curves_run2.pdf",width = 3.5,height = 3.5,useDingbats = F)
partA = reg_hit_stats %>% filter(Metadata_run =="CS_run2")
partB = reg_hit_stats %>% filter(Metadata_run =="CS_run3") %>% filter(Metadata_scheme=="random2")
data = rbind(partA,partB) %>% filter()
data$pool_color = as.numeric(as.character(data$pool_size))
ggplot(data,aes(y=tpr,x= fpr,color=pool_color)) +geom_line(aes(group=pool_size))+ theme_classic() + ylim(0,1) + xlim(0,0.65) +
  ggtitle("Run 2") + scale_color_viridis(discrete = F,trans="log2") +labs(color="Pool size")+ geom_abline(linetype = "dashed")
# dev.off()
# dev.off()
```


```{r}
data = reg_hit_stats %>% filter(permute_threshold !=0) %>% filter(Metadata_run=="CS_run1")
ggplot(data,aes(y=precision,x=recall,color=pool_size)) +geom_line()+ theme_classic() + ylim(0,1) + xlim(0,1)
```


```{r}

data = reg_hit_stats %>% filter(pool_size == 3) %>% arrange(permute_threshold)
ggplot(data,aes(y=precision,x= recall,color=permute_threshold)) + geom_point() + geom_line()+ theme_classic()

```




```{r}
pdf("regression_summary_stats/tpr.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=tpr  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('True positive rate') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None") + ylim(0,1)
dev.off()

pdf("regression_summary_stats/fpr.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=fpr  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('False positive rate') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None") + ylim(0,1)
dev.off()

pdf("regression_summary_stats/tp.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=tp  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('True positives') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/fp.pdf",width = 2.75,height = 2.5,useDingbats = F)

ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=fp  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('False positives') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/tn.pdf",width = 2.75,height = 2.5,useDingbats = F)

ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=tn  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('True negatives') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/fn.pdf",width = 2.75,height = 2.5,useDingbats = F)

ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=fn  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('False negatives') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method='lm') +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```


# Looking at the the hits from compressed that are mean + 2 std deve above




```{r}
pdf("regression_summary_stats/top_hits_num_sig_leiden.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_top_hits*percent_top_sig_leiden  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num of sig leiden in top hits') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/top_hits_percent_sig_leiden.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=percent_top_sig_leiden  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Percent of top CS hits sig in GT') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```


```{r}
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_top_hits  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num top hitsT') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
```

```{r}

```



# Number of hits from compressed

```{r}
reg_
```



```{r}
# total number of nominated hits
pdf("regression_summary_stats/total_num_hits_by_stringency.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_cs_hits  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num CS hits') + 
  xlab("Pool size") + theme_cowplot() + geom_smooth(method="lm",se=F) +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/total_num_hits_by_stringency_no_title.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_cs_hits  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num CS hits') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  # ggtitle(paste0("Number of hits nominated by CS"))+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/num_GT_hits_by_stringency_no_legend.pdf",width = 2.75,height = 2.5,useDingbats = F)
# Number of GT leiden sig
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_gt_pheno_sig_in_cs ,color=permute_threshold )) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method="lm",se=F) +
  # ggtitle(paste0("Number of GT leiden sig found by CS"))+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=6),legend.position = "None")
dev.off()

```

# Percent of nominated that is GT at differnet stringency
```{r}
# Fraction fo CS that are GT leiden
pdf("regression_summary_stats/fraction_of_total_hits_that_are_GT_hits_by_stringency_no_legend.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=percent_of_cs_that_is_gt_leiden,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Fraction') +
  xlab("Pool size") + theme_cowplot() + geom_smooth(method="lm",se=F) +ylim(0,1) +
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```


```{r}

```




# GT  Correlations

```{r}
pdf("regression_summary_stats/pearson_01.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats_01,aes(x=num_drugs_per_pool,y=pearson_gt_mahala_cs_perm_reg_l1_norm)) +
  geom_point() + scale_x_continuous(trans='log2') + ylab('Pearson correlation') +
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() + ylim(0,1) +
  ggtitle("Pearson correlation between the GT Mahalanobis distances &\nthe L1 norms of regression coeficients ")+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```



```{r}
pdf("regression_summary_stats/pearson_by_stringency.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=pearson_gt_mahala_cs_perm_reg_l1_norm,color=permute_threshold)) +
  geom_point() + scale_x_continuous(trans='log2') + ylab('Pearson correlation') +
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() + ylim(-0.1,1) +
  ggtitle("Pearson correlation between the GT Mahalanobis distances &\nthe L1 norms of regression coeficients ")+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()


pdf("regression_summary_stats/pearson_by_stringency_no_title.pdf",width = 2.75,height = 2.5,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=pearson_gt_mahala_cs_perm_reg_l1_norm,color=permute_threshold)) +
  geom_point() + scale_x_continuous(trans='log2') + ylab('Pearson correlation') +
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() + ylim(-0.1,1) +
  # ggtitle("Pearson correlation between the GT Mahalanobis distances &\nthe L1 norms of regression coeficients ")+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

pdf("regression_summary_stats/spearman_by_stringency.pdf",width = 2.75,height = 2.75,useDingbats = F)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=spearman_gt_mahala_cs_perm_reg_l1_norm,color=permute_threshold)) +
  geom_point() + scale_x_continuous(trans='log2') + ylab('Spearman correlation') +
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() + ylim(-0.1,1) +
  ggtitle("Spearman correlation between the GT Mahalanobis distances &\nthe L1 norms of regression coeficients ")+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```

# Top N drugs from mahala (5,10,32)


```{r}

n = 5
pdf(paste0("regression_summary_stats/mahla_top",n,".pdf"),useDingbats = F,width=2.75,height=2.75)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=percent_top5_mahala  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Percent of top mahala') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method="lm",se=F) + ylim(0,1) + 
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

n = 10
pdf(paste0("regression_summary_stats/mahla_top",n,".pdf"),useDingbats = F,width=2.75,height=2.75)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=percent_top10_mahala ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Percent of top mahala') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method="lm",se=F) +ylim(0,1) + 
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()

n = 32
pdf(paste0("regression_summary_stats/mahla_top",n,".pdf"),useDingbats = F,width=2.75,height=2.75)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=percent_top32_mahala  ,color=permute_threshold)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Percent of top mahala') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth(method="lm",se=F) +ylim(0,1) + 
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=10),axis.text = element_text(size=8),legend.position = "None")
dev.off()
```

# Recovering leiden sig

```{r}

ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_gt_pheno_sig_in_cs ,color=Metadata_compression_fctr,shape =Metadata_replicates_fctr )) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  ggtitle(paste0("Number of GT leiden sig found by CS"))+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=8),axis.text = element_text(size=6),legend.position = "None")


pdf("regression_summary_stats/frac_gt_leiden_sig_found.pdf",useDingbats = F,width=2.75,height=2.75)
temp = reg_hit_stats
temp$sig_color = "not significant"
temp$p_adjusted = p.adjust(temp$pval_gt_pheno_sig_in_cs,method="fdr")
temp$sig_color[temp$p_adjusted < 0.05] = "significant"
ggplot(temp,aes(x=num_drugs_per_pool,y=frac_gt_pheno_sig_in_cs,color=sig_color)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Fraction GT leiden sig') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + 
  ggtitle(paste0("Fraction of GT leiden sig found by CS\nSignificance relative to randomly finding N (same as reg) hits"))+
  labs(color="Hypergeometric\ntest")+
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6))
dev.off()

pdf("regression_summary_stats/frac_gt_leiden_sig_found_no_legend.pdf",useDingbats = F,width=2.75.5,height=2.75)
temp = reg_hit_stats
temp$sig_color = "not significant"
temp$p_adjusted = p.adjust(temp$pval_gt_pheno_sig_in_cs,method="fdr")
temp$sig_color[temp$p_adjusted < 0.05] = "significant"
ggplot(temp,aes(x=num_drugs_per_pool,y=frac_gt_pheno_sig_in_cs,color=sig_color)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Fraction GT leiden sig') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + 
  ggtitle(paste0("Fraction of GT leiden sig found by CS\nSignificance relative to randomly finding N (same as reg) hits"))+
  labs(color="Hypergeometric\ntest")+
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6),
        legend.position = "none")
  
dev.off()
```

# Sample saving

```{r}
# pdf("regression_summary_stats/num_hits_nominated_by_CS.pdf",useDingbats = F,width=2.75,height=2.75)
ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=num_cs_hits  ,color=Metadata_compression_fctr,shape =Metadata_replicates_fctr)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num CS hits') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
  ggtitle(paste0("Number of hits nominated by CS"))+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=8),axis.text = element_text(size=6),legend.position = "None")
# dev.off()

# pdf("regression_summary_stats/sample_savings.pdf",useDingbats = F,width=2.75,height=2.75)
# ggplot(reg_hit_stats,aes(x=num_drugs_per_pool,y=sample_savings,color=Metadata_compression_fctr,shape =Metadata_replicates_fctr )) + 
#   geom_point() + scale_x_continuous(trans='log2') + ylab('Fraction of total samples needed') + ylim(0,1) +
#   xlab("Number of perturbations in pool") + theme_cowplot() + geom_smooth() +
#   ggtitle(paste0("Fraction of samples needed for CS+validation\ncompared to a GT screen of all compounds"))+
#   theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=8),axis.text = element_text(size=6),legend.position = "None")
# dev.off()
```

# Comparing the number of leiden cs found vs the sample savings

```{r}
temp = reg_hit_stats
temp$Metadata_compression_fctr = factor(temp$Metadata_compression,levels=c(2.0,4.0,8.0,16.0,32.0))
temp$Metadata_replicates_fctr = factor(temp$Metadata_replicates,levels=c(3,5,7))

ggplot(temp,aes(x=num_drugs_per_pool,y=num_gt_pheno_sig_in_cs / sample_savings,color=Metadata_compression)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig / sample savings') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + 
  ggtitle(paste0("Num. GT leiden sig found / sample saving"))+
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6))

mean_stats = temp %>% group_by(Metadata_compression_fctr,Metadata_replicates_fctr) %>%
  summarize(hits_over_savings = mean(num_gt_pheno_sig_in_cs)/mean(sample_savings),
            num_drugs_per_pool =num_drugs_per_pool,
            Metadata_compression=Metadata_compression)
pdf("regression_summary_stats/mean_hits_over_savings_without_legend.pdf",useDingbats = F,width=2.75,height=2.75)
ggplot(mean_stats,aes(x=num_drugs_per_pool,y=hits_over_savings,color=Metadata_compression_fctr,shape=Metadata_replicates_fctr)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig / sample savings') + 
  xlab("Number of perturbations in pool") + theme_cowplot() + 
  ggtitle(paste0("Mean Num. GT leiden sig found / sample saving"))+
  theme(plot.title = element_text(size=10,face="plain"),axis.title = element_text(size=8),axis.text = element_text(size=6),legend.position = "None")
dev.off()

pdf("regression_summary_stats/mean_hits_over_savings_by_compression.pdf",useDingbats = F,width=2.75,height=2.75)
ggplot(mean_stats,aes(x=Metadata_compression,y=hits_over_savings,color=Metadata_compression_fctr,shape=Metadata_replicates_fctr)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig / sample savings') + 
  xlab("Compression factor") + theme_cowplot() + 
  ggtitle(paste0("Mean Num. GT leiden sig found / sample saving")) +
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6))
dev.off()

pdf("regression_summary_stats/mean_hits_over_savings_no_legend_by_compression.pdf",useDingbats = F,width=2.75,height=2.75)
ggplot(mean_stats,aes(x=Metadata_compression,y=hits_over_savings,color=Metadata_compression_fctr,shape=Metadata_replicates_fctr)) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig / sample savings') + 
  xlab("Compression factor") + theme_cowplot() + 
  ggtitle(paste0("Mean Num. GT leiden sig found / sample saving")) +
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6),
        legend.position = "None")
dev.off()


ggplot(reg_hit_stats,aes(x=Metadata_compression,y=num_gt_pheno_sig_in_cs / sample_savings )) + 
  geom_point() + scale_x_continuous(trans='log2') + ylab('Num GT leiden sig / sample savings') + 
  xlab("Compression factor") + theme_cowplot() + geom_smooth(span=1.0) + 
  ggtitle(paste0("Num. GT leiden sig found / sample saving"))+
  theme(plot.title = element_text(size=10),axis.title = element_text(size=8),axis.text = element_text(size=6))

```




